# Generated by Django 4.1.7 on 2023-03-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('from_date', models.DateTimeField(verbose_name='from_date')),
                ('to_date', models.DateTimeField(verbose_name='to_date')),
                ('venue', models.TextField(blank=True, null=True)),
                ('max_participants', models.PositiveIntegerField(default=2)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
