# Generated by Django 4.1.7 on 2023-03-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_id_event_created_at_event_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
