# fly.toml

app = "django-images"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8000"         # new

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000  # changed
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

[deploy]
  release_command = "python manage.py migrate --noinput"