# Generated by Django 4.1.7 on 2023-03-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
