# Generated by Django 4.1.7 on 2023-03-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_eventticket_pdf_alter_eventticket_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventticket',
            name='is_valid',
        ),
    ]
